[tool.poetry]
name = "MasterThesis"
version = "1.0.0"
description = "Code for Master Thesis of Remy Duijsens"
authors = ["remdui <remyduijsens@gmail.com>"]
license = "MIT"
repository = "https://github.com/remdui/MasterThesis"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.3"
torch = "^2.5.0"
pandas = "^2.2.3"
numpy = "^2.1.2"
scipy = "^1.14.1"
scikit-learn = "^1.5.2"
PyYAML = "^6.0.2"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
