[tool.poetry]
name = "MasterThesis"
version = "1.0.0"
description = "Code for Master Thesis of Remy Duijsens"
authors = ["remdui <remyduijsens@gmail.com>"]
license = "MIT"
repository = "https://github.com/remdui/MasterThesis"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.3"
torch = "2.5.0"
pandas = "2.2.3"
numpy = "2.1.2"
scipy = "1.14.1"
scikit-learn = "1.5.2"
PyYAML = "6.0.2"
types-PyYAML = "6.0.2"
pandas-stubs = "2.2.3.241009"

[tool.poetry.group.dev.dependencies]
pylint = "3.3.1"
mypy = "1.13.0"
pydocstringformatter = "0.7.3"
black = "24.10.0"
isort = "5.13.2"
ruff = "0.7.1"
autoflake = "2.3.1"

[tool.poetry.group.test.dependencies]
pytest = "8.3.3"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
