system:
  checkpoint: ''
  checkpoint_interval: 5
  data_dir: ./data
  device: cpu
  log_dir: ./logs
  models_dir: ./models
  num_workers: 4
  output_dir: ./output
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder design experiment setup
  name: vae_basic
  version: 1
dataset:
  covariates:
  - age
  - sex
  input_data: generated_data.rds
  data_type: tabular
  shuffle: true
  test_split: 0.1
  train_split: 0.7
  val_split: 0.2
  enable_preprocessing: false
  preprocessors:
  - name: DataCleaningPreprocessor
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationPreprocessor
    params:
      method: min-max
train:
  batch_size: 32
  early_stopping: true
  early_stopping_metric: loss
  early_stopping_min_delta: 0.0
  early_stopping_patience: 10
  epochs: 100
  gradient_clipping: 5.0
  learning_rate: 0.001
  log_interval: 10
  loss_function: bce_kld
  lr_warmup_steps: 500
  mixed_precision: false
  optimizer: adam
  weight_decay: 0.0001
model:
  encoder: mlp
  decoder: mlp
  activation_function: relu
  beta: 1.0
  covariate_embedding: input_embedding
  dropout_rate: 0.5
  hidden_dim:
  - 128
  - 64
  - 32
  kl_annealing: true
  kl_annealing_steps: 1000
  latent_dim: 10
  normalization_layer: batch_norm
  reconstruction_loss_weight: 1.0
  save_model: true
  save_model_interval: 10
  save_model_path: model.pth
  weight_initialization: xavier
scheduler:
  gamma: 0.1
  scheduler: steplr
  step_size: 10
