system:
  data_dir: ./data
  device: cuda
  log_dir: ./logs
  models_dir: ./models
  num_workers: 4
  output_dir: ./output
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder validation experiment setup
  name: vae_val_mnist
  version: 1
dataset:
  covariates:
  - '0' # '0' is the label column
  input_data: mnist.csv
  data_type: tabular
  shuffle: true
  test_split: 0.0
  train_split: 0.9
  val_split: 0.1
  enable_transforms: true
  transforms:
  - name: DataCleaningTransform
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationTransform
    params:
      method: min-max
train:
  batch_size: 32
  epochs: 10
  loss_function: bce_vae
  optimizer: adam
  mixed_precision: false
  save_model: true
  checkpoint:
    save_checkpoint: true
    interval: 20
    use_checkpoint: false
    checkpoint: ''
  early_stopping:
    enabled: true
    metric: loss
    min_delta: 0.0
    patience: 10
  regularization:
    gradient_clipping: 5.0
    weight_decay: 0.0001
  scheduler:
    learning_rate: 0.001
    warmup_steps: 500
    method: step
    gamma: 0.1
    step_size: 10
    kl_annealing: true
    kl_annealing_steps: 1000
model:
  architecture: vae
  components:
    vae:
      encoder: mlp
      decoder: mlp
      latent_dim: 32
      covariate_embedding: input_embedding
  hidden_layers:
  - 1024
  - 512
  - 256
  activation_function: relu
  final_activation_function: sigmoid
  normalization_layer: batch_norm
  weight_initialization: xavier
  batch_norm:
    enabled: true
    eps: 1.0e-05
    momentum: 0.1
    affine: true
    track_running_stats: true
  linear:
    bias: true
  dropout:
    enabled: true
    p: 0.2
    inplace: false
validation:
  model: 'vae_val_mnist_v1.pt'
  baseline_model: null
  data_representation: image
  metrics:
  - mse
  - mae
  image:
    length: 28
    width: 28
    num_visual_samples: 3
    save_image_samples: true
    show_image_samples: false
