dataset:
  num_covariates: 2
  raw_data: generated_data.rds
  shuffle: true
  test_split: 0.1
  train_split: 0.7
  val_split: 0.2
  input_data: input_data.csv
  data_converter: RdsToCsvConverter
  enable_preprocessing: true
  preprocessors:
  - name: DataCleaningPreprocessor
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationPreprocessor
    params:
      method: min-max
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder design experiment setup
  version: 1
  name: vae_design
model:
  activation_function: relu
  beta: 1.0
  covariate_embedding: input_embedding
  decoder: mlp
  dropout_rate: 0.5
  encoder: mlp
  hidden_dim:
  - 100
  - 50
  - 25
  kl_annealing: true
  kl_annealing_steps: 1000
  latent_dim: 15
  normalization_layer: batch_norm
  reconstruction_loss_weight: 1.0
  save_model: true
  save_model_interval: 10
  save_model_path: model.pth
  weight_initialization: xavier
scheduler:
  gamma: 0.1
  scheduler: steplr
  step_size: 10
system:
  checkpoint: ''
  checkpoint_interval: 5
  data_dir: ./data
  device: cuda
  log_dir: ./logs
  model_dir: ./models
  num_workers: 4
  output_dir: ./output
train:
  batch_size: 32
  early_stopping: true
  early_stopping_metric: loss
  early_stopping_min_delta: 0.0
  early_stopping_patience: 10
  epochs: 10
  gradient_clipping: 5.0
  learning_rate: 0.001
  log_interval: 10
  loss_function: bce_kld
  lr_warmup_steps: 500
  mixed_precision: false
  optimizer: adam
  weight_decay: 0.0001
