system:
  data_dir: ./data
  device: cuda
  log_dir: ./logs
  models_dir: ./models
  num_workers: 4
  output_dir: ./output
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder validation experiment setup
  name: vae_val_mnist
  version: 1
dataset:
  covariates:
  - '0' # '0' is the label column
  input_data: mnist.csv
  data_type: tabular
  image_type: grayscale
  internal_file_format: hdf
  pin_memory: true
  shuffle: true
  test_split: 0.0
  train_split: 0.9
  val_split: 0.1
  enable_transforms: true
  transforms:
  - name: DataCleaningTransform
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationTransform
    params:
      method: min-max
train:
  batch_size: 128
  epochs: 200
  mixed_precision: false
  gradient_clipping: false
  save_model: true
  save_format: safetensors
  checkpoint:
    save_checkpoint: true
    interval: 20
    use_checkpoint: false
    checkpoint: ''
  early_stopping:
    enabled: true
    metric: loss
    min_delta: 0.0
    patience: 10
  loss_function: bce_vae
  loss_function_params:
    bce_vae:
      reduction: sum
    mse_vae:
      reduction: sum
    l1:
      reduction: sum
    mse:
      reduction: sum
    cross_entropy:
      ignore_index: -100
      reduction: sum
      label_smoothing: 0.0
    ctc:
      blank: 0
      reduction: sum
      zero_infinity: false
    nll:
      ignore_index: -100
      reduction: sum
    poisson_nll:
      log_input: true
      full: false
      eps: 1.0e-06
      reduction: sum
    gaussian_nll:
      full: false
      eps: 1.0e-06
      reduction: sum
    kldiv:
      reduction: sum
      log_target: false
    bce:
      reduction: sum
    bce_with_logits:
      reduction: sum
    margin_ranking:
      margin: 0.0
      reduction: sum
    hinge_embedding:
      margin: 1.0
      reduction: sum
    multi_label_margin:
      reduction: sum
    huber:
      reduction: sum
      delta: 1.0
    smooth_l1:
      reduction: sum
      beta: 1.0
    soft_margin:
      reduction: sum
    multi_label_soft_margin:
      reduction: sum
    cosine_embedding:
      margin: 0.0
      reduction: sum
    multi_margin:
      p: 1.0
      margin: 1.0
      reduction: sum
    triplet_margin:
      margin: 1.0
      p: 2.0
      eps: 1.0e-06
      swap: false
      reduction: sum
    triplet_margin_with_distance:
      margin: 1.0
      swap: false
      reduction: sum
  scheduler: plateau
  scheduler_params:
    default:
      last_epoch: -1
    lambda:
      lr_lambda: 'lambda epoch: 0.95 ** epoch'
      last_epoch: -1
    multiplicative:
      lr_lambda: 'lambda epoch: 0.95'
      last_epoch: -1
    step:
      step_size: 10
      gamma: 0.1
      last_epoch: -1
    multistep:
      milestones:
      - 30
      - 80
      gamma: 0.1
      last_epoch: -1
    constant:
      factor: 0.3333333333333333
      total_iters: 5
      last_epoch: -1
    linear:
      start_factor: 0.3333333333333333
      end_factor: 1.0
      total_iters: 5
      last_epoch: -1
    exponential:
      gamma: 0.95
      last_epoch: -1
    polynomial:
      total_iters: 5
      power: 1.0
      last_epoch: -1
    cosineannealing:
      T_max: 10
      eta_min: 0.0
      last_epoch: -1
    plateau:
      mode: min
      factor: 0.1
      patience: 3
      threshold: 0.0001
      threshold_mode: rel
      cooldown: 0
      min_lr: 0
      eps: 1.0e-08
    cyclic:
      base_lr: 0.001
      max_lr: 0.01
      step_size_up: 2000
      step_size_down: null
      mode: triangular
      gamma: 1.0
      scale_fn: null
      scale_mode: cycle
      cycle_momentum: true
      base_momentum: 0.8
      max_momentum: 0.9
      last_epoch: -1
    onecycle:
      max_lr: 0.1
      total_steps: null
      epochs: null
      steps_per_epoch: null
      pct_start: 0.3
      anneal_strategy: cos
      cycle_momentum: true
      base_momentum: 0.85
      max_momentum: 0.95
      div_factor: 25.0
      final_div_factor: 10000.0
      three_phase: false
      last_epoch: -1
    cosineannealingwarmrestarts:
      T_0: 10
      T_mult: 2
      eta_min: 0.0
      last_epoch: -1
  optimizer: adamw
  optimizer_params:
    adam:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
      weight_decay: 0.0
      amsgrad: false
    adamw:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
      weight_decay: 0.01
      amsgrad: false
    sgd:
      lr: 0.001
      momentum: 0.0
      dampening: 0.0
      weight_decay: 0.0
      nesterov: false
    adadelta:
      lr: 1.0
      rho: 0.9
      eps: 1.0e-06
      weight_decay: 0
    adafactor:
      lr: 0.01
      beta2_decay: -0.8
      eps:
        - null
        - 0.001
      d: 1.0
      weight_decay: 0.0
    adagrad:
      lr: 0.01
      lr_decay: 0
      weight_decay: 0
      initial_accumulator_value: 0
      eps: 1.0e-10
    sparse_adam:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
    adamax:
      lr: 0.002
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
      weight_decay: 0
    asgd:
      lr: 0.01
      lambd: 0.0001
      alpha: 0.75
      t0: 1000000.0
      weight_decay: 0
    lbfgs:
      lr: 1
      max_iter: 20
      max_eval: null
      tolerance_grad: 1.0e-07
      tolerance_change: 1.0e-09
      history_size: 100
      line_search_fn: null
    nadam:
      lr: 0.002
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
      weight_decay: 0
      momentum_decay: 0.004
      decoupled_weight_decay: false
    radam:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1.0e-08
      weight_decay: 0
      decoupled_weight_decay: false
    rmsprop:
      lr: 0.01
      alpha: 0.99
      eps: 1.0e-08
      weight_decay: 0
      momentum: 0
      centered: false
    rprop:
      lr: 0.01
      etas:
        - 0.5
        - 1.2
      step_sizes:
        - 1.0e-06
        - 50
model:
  architecture: vae
  components:
    vae:
      encoder: mlp
      decoder: mlp
      latent_dim: 16
      covariate_embedding: input_embedding
  hidden_layers:
  - 512
  - 256
  - 128
  weight_initializer: he_normal
  dropout:
    enabled: true
    p: 0.2
    inplace: false
  normalization_layer: batchnorm1d
  normalization_layer_params:
    batchnorm1d:
      eps: 1.0e-05
      momentum: 0.1
      affine: true
      track_running_stats: true
    batchnorm2d:
      eps: 1.0e-05
      momentum: 0.1
      affine: true
      track_running_stats: true
    batchnorm3d:
      eps: 1.0e-05
      momentum: 0.1
      affine: true
      track_running_stats: true
    groupnorm:
      eps: 1.0e-05
      affine: true
    syncbatchnorm:
      eps: 1.0e-05
      momentum: 0.1
      affine: true
      track_running_stats: true
    instancenorm1d:
      eps: 1.0e-05
      momentum: 0.1
      affine: false
      track_running_stats: false
    instancenorm2d:
      eps: 1.0e-05
      momentum: 0.1
      affine: false
      track_running_stats: false
    instancenorm3d:
      eps: 1.0e-05
      momentum: 0.1
      affine: false
      track_running_stats: false
    layernorm:
      eps: 1.0e-05
      elementwise_affine: true
    localresponsenorm:
      alpha: 0.0001
      beta: 0.75
      k: 1.0
    rmsnorm:
      eps: 1.0e-08
      elementwise_affine: true
  activation_function: relu
  final_activation_function: sigmoid
  activation_function_params:
    elu:
      alpha: 1.0
    hardshrink:
      lambd: 0.5
    hardtanh:
      min_val: -1.0
      max_val: 1.0
    leakyrelu:
      negative_slope: 0.01
    prelu:
      num_parameters: 1
      init: 0.25
    rrelu:
      lower: 0.125
      upper: 0.333
      inplace: false
    celu:
      alpha: 1.0
    gelu:
      approximate: none
    softplus:
      beta: 1.0
      threshold: 20.0
    softshrink:
      lambd: 0.5
    threshold:
      threshold: 1.0
      value: 0.0
    glu:
      dim: -1
    adaptivelogsoftmaxwithloss:
      cutoffs:
      - 10
      - 20
      - 30
      div_value: 4.0
      head_bias: false
    logsoftmax:
      dim: null
    softmax:
      dim: null
    softmin:
      dim: null
validation:
  model: 'vae_val_mnist_v1.safetensors'
  baseline_model: null
  data_representation: image
  metrics:
  - mse
  - mae
  image:
    length: 28
    width: 28
    num_visual_samples: 3
    save_image_samples: true
    show_image_samples: false
