dataset:
  covariates:
  - age
  - sex
  shuffle: true
  test_split: 0.1
  train_split: 0.8
  val_split: 0.1
  data_type: tabular
  input_data: generated_data.rds
  enable_preprocessing: true
  preprocessors:
  - name: DataCleaningPreprocessor
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationPreprocessor
    params:
      method: min-max
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder design experiment setup
  version: 1
  name: vae_design
model:
  encoder: mlp
  decoder: mlp
  activation_function: relu
  covariate_embedding: input_embedding
  dropout_rate: 0.5
  hidden_dim:
  - 512
  - 256
  - 128
  latent_dim: 32
  normalization_layer: batch_norm
  weight_initialization: xavier
scheduler:
  gamma: 0.1
  scheduler: steplr
  step_size: 10
system:
  data_dir: ./data
  device: cuda
  log_dir: ./logs
  model_dir: ./models
  num_workers: 4
  output_dir: ./output
train:
  batch_size: 64
  early_stopping: true
  early_stopping_metric: loss
  early_stopping_min_delta: 0.0
  early_stopping_patience: 10
  epochs: 200
  gradient_clipping: 5.0
  learning_rate: 0.001
  log_interval: 10
  loss_function: bce_kld
  lr_warmup_steps: 500
  kl_annealing: true
  kl_annealing_steps: 1000
  mixed_precision: false
  optimizer: adam
  save_model: true
  save_checkpoint: true
  checkpoint_interval: 50
  use_checkpoint: false
  checkpoint: ''
  weight_decay: 0.0001
