system:
  data_dir: ./data
  device: cuda
  log_dir: ./logs
  models_dir: ./models
  num_workers: 4
  output_dir: ./output
general:
  debug: false
  log_level: INFO
  seed: 42
  verbose: false
meta:
  config_version: 2
  description: Variational Autoencoder validation experiment setup
  name: vae_val_mnist
  version: 1
dataset:
  covariates: []
  input_data: generated_data.rds
  data_type: tabular
  shuffle: true
  test_split: 0.0
  train_split: 0.9
  val_split: 0.1
  enable_preprocessing: true
  preprocessors:
  - name: DataCleaningPreprocessor
    params:
      drop_na: true
      remove_duplicates: true
  - name: NormalizationPreprocessor
    params:
      method: min-max
train:
  batch_size: 32
  epochs: 100
  loss_function: bce_kld
  optimizer: adam
  mixed_precision: false
  save_model: true
  checkpoint:
    save_checkpoint: true
    interval: 20
    use_checkpoint: false
    checkpoint: ''
  early_stopping:
    enabled: true
    metric: loss
    min_delta: 0.0
    patience: 10
  regularization:
    gradient_clipping: 5.0
    weight_decay: 0.0001
  scheduler:
    learning_rate: 0.001
    warmup_steps: 500
    method: steplr
    gamma: 0.1
    step_size: 10
    kl_annealing: true
    kl_annealing_steps: 1000
model:
  encoder: mlp
  decoder: mlp
  hidden_dim:
  - 512
  - 256
  - 128
  latent_dim: 16
  activation_function: relu
  covariate_embedding: input_embedding
  normalization_layer: batch_norm
  weight_initialization: xavier
  batch_norm:
    enabled: true
    eps: 1.0e-05
    momentum: 0.1
    affine: true
    track_running_stats: true
  linear:
    bias: true
  dropout:
    enabled: true
    p: 0.2
    inplace: false
